version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App_Proj4"
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    container_name: "MySQL_Database_Proj4"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      SECRET_KEY: $SECRET_KEY
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro


